refkit: support whole-disk encryption with TPM 2.0
During installation, TPM 1.2 or 2.0 have to be chosen explicitly via
the "tpm" env variable. Detecting whether a /dev/tpm0 supports TPM 1.2
or 2.0 turned out to be
tricky (https://github.com/intel/tpm2-tools/issues/604) and probably
isn't worth the effort and potential error cases.

Conceptually TPM 2.0 supports is similar to the one for 1.2, with one
exception: because it is possible to use NVRAM without taking
ownership and taking ownership with known passwords wouldn't provide
any advantages, the TPM 2.0 support code skips that step.

Testing switches to swtpm2 for both the existing TPM1.2 test and the
new TPM2.0 test. It just gets parameterized differently.

Signed-off-by: Patrick Ohly <patrick.ohly@intel.com>