refkit_security_flags.inc: avoid FORTIFY_SOURCE for iotivity
OE-core is introducing -D_FORTIFY_SOURCE=2 as default. iotivity fails
to build with that because one example doesn't get the necessary -O:

| /fast/build/refkit/intel-corei7-64/tmp-glibc/work/corei7-64-refkit-linux/iotivity/1.2.1-r0/recipe-sysroot/usr/include/features.h:373:4: error: #warning _FORTIFY_SOURCE requires compiling with optimization (-O) [-Werror=cpp]
|  #  warning _FORTIFY_SOURCE requires compiling with optimization (-O)
|     ^~~~~~~
| cc1: all warnings being treated as errors
| scons: *** [out/yocto/x86_64/release/resource/oc_logger/examples/c_test_logging.o] Error 1
| scons: building terminated because of errors.
| ERROR: scons build execution failed.

A better solution would be to compile all of iotivity with -O.

Signed-off-by: Patrick Ohly <patrick.ohly@intel.com>